version: '3'
services:
  db:
    image: postgres:14
    ports:
      - '${HOST_PORT}:5432'
    restart: always
    environment:
      POSTGRES_USER: ${USER_NAME}
      POSTGRES_PASSWORD: ${USER_PW}
      POSTGRES_DB: ${DB_NAME}
    container_name: ${CONTAINER_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
volumes:
  pgdata: